export const data = [
  {
    id: 34042,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "INDENNIZZO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 113,
    package_name: null,
  },
  {
    id: 34041,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "IMPRESA:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 112,
    package_name: null,
  },
  {
    id: 34040,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "FRANCHIGIA: ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 111,
    package_name: null,
  },
  {
    id: 34039,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "FASCICOLO INFORMATIVO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 110,
    package_name: null,
  },
  {
    id: 34038,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ESCLUSIONI: ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 109,
    package_name: null,
  },
  {
    id: 34037,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "DECORRENZA DELLA GARANZIA:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 108,
    package_name: null,
  },
  {
    id: 34036,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "CONTRAENTE:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 107,
    package_name: null,
  },
  {
    id: 34022,
    parent_id: 34021,
    product_id: 276,
    benchmark_clause_id: null,
    title: "1\tDanni     suscettibili     di     riparazione     (DANNO PARZIALE)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 93,
    package_name: null,
  },
  {
    id: 34020,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 5 - CAPITALE ASSICURATO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 91,
    package_name: null,
  },
  {
    id: 34019,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 4- BENI NON ASSICURATI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 90,
    package_name: null,
  },
  {
    id: 34008,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 6) Premio",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 79,
    package_name: null,
  },
  {
    id: 34043,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ISVAP",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 114,
    package_name: null,
  },
  {
    id: 34007,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 5) Dichiarazioni del Contraente.",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 78,
    package_name: null,
  },
  {
    id: 34006,
    parent_id: 34003,
    product_id: 276,
    benchmark_clause_id: null,
    title: "DANNO PARZIALE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 77,
    package_name: null,
  },
  {
    id: 33993,
    parent_id: 33992,
    product_id: 276,
    benchmark_clause_id: null,
    title:
      "DANNI INDIRETTI (Estensione della garanzia alle perdite economiche derivanti da intralcio-fermo dell’attività)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 64,
    package_name: null,
  },
  {
    id: 33992,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "APPENDICE  @ Office",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 63,
    package_name: null,
  },
  {
    id: 33988,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art.17 DIRITTO DI RIVALSA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 59,
    package_name: null,
  },
  {
    id: 33987,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art.16 PAGAMENTO DELLE INDENNITÀ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 58,
    package_name: null,
  },
  {
    id: 33986,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 15 LIMITE MASSIMO DI RISARCIMENTO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 57,
    package_name: null,
  },
  {
    id: 33985,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 14 ASSICURAZIONE PRESSO DIVERSI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 56,
    package_name: null,
  },
  {
    id: 33994,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 1) Oggetto dell’estensione Danni Indiretti",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 65,
    package_name: null,
  },
  {
    id: 33973,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 1       OGGETTO DELL'ASSICURAZIONE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 44,
    package_name: null,
  },
  {
    id: 33991,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 20     FORO COMPETENTE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 62,
    package_name: null,
  },
  {
    id: 33990,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 19 INOPPONIBILITÀ ALLA SOCIETÀ DEGLI ATTI DI RILEVAZIONE DEL DANNO E SUCCESSIVI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 61,
    package_name: null,
  },
  {
    id: 33972,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "11)  CONDIZIONI GENERALI D’ASSICURAZIONE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 43,
    package_name: null,
  },
  {
    id: 33952,
    parent_id: 33951,
    product_id: 276,
    benchmark_clause_id: null,
    title: "1)    SOMMA  ASSICURATA,  LIMITI  DI  RISARCIMENTO, RIDUZIONE DELLA SOMMA RISARCIBILE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 23,
    package_name: null,
  },
  {
    id: 33949,
    parent_id: 33946,
    product_id: 276,
    benchmark_clause_id: null,
    title: "14. Arbitrato",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 20,
    package_name: null,
  },
  {
    id: 33937,
    parent_id: 33936,
    product_id: 276,
    benchmark_clause_id: null,
    title:
      "Garanzia accessoria Perdite Economiche derivanti da intralcio-fermo dell’attività operante esclusivamente se presente in polizza:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 8,
    package_name: null,
  },
  {
    id: 33960,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "4)    BENI ESCLUSI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 31,
    package_name: null,
  },
  {
    id: 33989,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 18  RECESSO IN CASO DI SINISTRO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 60,
    package_name: null,
  },
  {
    id: 33971,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "10)  DICHIARAZIONI DEL CONTRAENTE/ASSICURATO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 42,
    package_name: null,
  },
  {
    id: 33950,
    parent_id: null,
    product_id: 276,
    benchmark_clause_id: null,
    title: "CONDIZIONI GENERALI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 21,
    package_name: null,
  },
  {
    id: 33996,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "a)  SOSPENSIONE  DELL’ATTIVITA’  LAVORATIVA (PARZIALE o TOTALE)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 67,
    package_name: null,
  },
  {
    id: 34035,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "CONDIZIONI PARTICOLARI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 106,
    package_name: null,
  },
  {
    id: 34034,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "CONDIZIONI GENERALI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 105,
    package_name: null,
  },
  {
    id: 34033,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ASSICURAZIONE DELLA RESPONSABILITA’ CIVILE GENERALE: ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 104,
    package_name: null,
  },
  {
    id: 34031,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ASSICURAZIONE: ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 102,
    package_name: null,
  },
  {
    id: 34030,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ASSICURATO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 101,
    package_name: null,
  },
  {
    id: 34029,
    parent_id: null,
    product_id: 276,
    benchmark_clause_id: null,
    title: "GLOSSARIO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 100,
    package_name: null,
  },
  {
    id: 34028,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 9 -MACCHINARI IN LEASING",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 99,
    package_name: null,
  },
  {
    id: 34018,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 3 - DEFINIZIONE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 89,
    package_name: null,
  },
  {
    id: 34017,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 2 - ESCLUSIONI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 88,
    package_name: null,
  },
  {
    id: 34005,
    parent_id: 34003,
    product_id: 276,
    benchmark_clause_id: null,
    title: "DANNO TOTALE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 76,
    package_name: null,
  },
  {
    id: 34004,
    parent_id: 34003,
    product_id: 276,
    benchmark_clause_id: null,
    title: "1)   RIMBORSO   DELLE   SPESE   GENERALI   FISSE   DEL CONTRAENTE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 75,
    package_name: null,
  },
  {
    id: 33984,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 13     ASSICURAZIONE PARZIALE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 55,
    package_name: null,
  },
  {
    id: 33983,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art.12      DETERMINAZIONE DEI DANNI RISARCIBILI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 54,
    package_name: null,
  },
  {
    id: 33982,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 11     VALUTAZIONE DEL DANNO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 53,
    package_name: null,
  },
  {
    id: 33981,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 10     ESAGERAZIONE DOLOSA DEL DANNO ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 52,
    package_name: null,
  },
  {
    id: 33970,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "9)    RICORSO TERZI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 41,
    package_name: null,
  },
  {
    id: 34032,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ASSICURAZIONE A PRIMO RISCHIO ASSOLUTO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 103,
    package_name: null,
  },
  {
    id: 33958,
    parent_id: 33956,
    product_id: 276,
    benchmark_clause_id: null,
    title: "B)  SOFTWARE, cioè",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 29,
    package_name: null,
  },
  {
    id: 33957,
    parent_id: 33956,
    product_id: 276,
    benchmark_clause_id: null,
    title: "A)  HARDWARE, cioè:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 28,
    package_name: null,
  },
  {
    id: 33948,
    parent_id: 33946,
    product_id: 276,
    benchmark_clause_id: null,
    title: "13. Reclami",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 19,
    package_name: null,
  },
  {
    id: 33959,
    parent_id: 33956,
    product_id: 276,
    benchmark_clause_id: null,
    title: "C)  SPESE EXTRA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 30,
    package_name: null,
  },
  {
    id: 33934,
    parent_id: 33930,
    product_id: 276,
    benchmark_clause_id: null,
    title: "B. INFORMAZIONI SUL CONTRATTO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 5,
    package_name: null,
  },
  {
    id: 34054,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "VALORE ASSICURATO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 125,
    package_name: null,
  },
  {
    id: 34027,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 8 - IMPIEGO MOBILE IN SEDE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 98,
    package_name: null,
  },
  {
    id: 34026,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 7 - ESTENSIONE AREA TERRITORIALE MONDO(*)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 97,
    package_name: null,
  },
  {
    id: 34025,
    parent_id: 34021,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Cumulo con altre somme assicurate",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 96,
    package_name: null,
  },
  {
    id: 34016,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 1 - GARANZIA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 87,
    package_name: null,
  },
  {
    id: 34015,
    parent_id: 33992,
    product_id: 276,
    benchmark_clause_id: null,
    title:
      "ASSICURAZIONE DEI PERSONAL COMPUTER PORTATILI appendice di estensione di copertura ai computer portatili",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 86,
    package_name: null,
  },
  {
    id: 34002,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Sono inoltre esclusi i danni:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 73,
    package_name: null,
  },
  {
    id: 34053,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "VALORE A NUOVO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 124,
    package_name: null,
  },
  {
    id: 34001,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "FRANCHIGIA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 72,
    package_name: null,
  },
  {
    id: 34000,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "MASSIMO INDENNIZZO GIORNALIERO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 71,
    package_name: null,
  },
  {
    id: 33980,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 9       OBBLIGO IN CASO DI  SINISTRO L'Assicurato deve:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 51,
    package_name: null,
  },
  {
    id: 33979,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 8       OBBLIGO E SPESE DI SALVATAGGIO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 50,
    package_name: null,
  },
  {
    id: 33978,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 7       ISPEZIONE AGLI ENTI ASSICURATI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 49,
    package_name: null,
  },
  {
    id: 33968,
    parent_id: 33964,
    product_id: 276,
    benchmark_clause_id: null,
    title: "danni ai programmi: ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 39,
    package_name: null,
  },
  {
    id: 33955,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "2)    GARANZIA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 26,
    package_name: null,
  },
  {
    id: 33947,
    parent_id: 33946,
    product_id: 276,
    benchmark_clause_id: null,
    title: "12. Sinistri - Liquidazione dell’indennizzo",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 18,
    package_name: null,
  },
  {
    id: 33945,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "11. Regime fiscale",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 16,
    package_name: null,
  },
  {
    id: 33943,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "9. Prescrizione e decadenza dei diritti derivanti dal contratto",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 14,
    package_name: null,
  },
  {
    id: 33969,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "8)    REINTEGRO DELLA SOMMA ASSICURATA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 40,
    package_name: null,
  },
  {
    id: 33933,
    parent_id: 33931,
    product_id: 276,
    benchmark_clause_id: null,
    title: "2. Informazioni sulla situazione patrimoniale dell’Impresa",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 4,
    package_name: null,
  },
  {
    id: 33932,
    parent_id: 33931,
    product_id: 276,
    benchmark_clause_id: null,
    title: "1. Informazioni generali",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 3,
    package_name: null,
  },
  {
    id: 33930,
    parent_id: null,
    product_id: 276,
    benchmark_clause_id: null,
    title: "NOTA INFORMATIVA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 1,
    package_name: null,
  },
  {
    id: 33944,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "10. Legge applicabile al contratto",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 15,
    package_name: null,
  },
  {
    id: 34055,
    parent_id: null,
    product_id: 276,
    benchmark_clause_id: null,
    title: "ARTICOLI DI LEGGE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 126,
    package_name: null,
  },
  {
    id: 34052,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "SURROGAZIONE:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 123,
    package_name: null,
  },
  {
    id: 34051,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "SOMMA ASSICURATA:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 122,
    package_name: null,
  },
  {
    id: 34050,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "SINISTRO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 121,
    package_name: null,
  },
  {
    id: 34049,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "SEZIONE DI POLIZZA:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 120,
    package_name: null,
  },
  {
    id: 34048,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "RIVALSA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 119,
    package_name: null,
  },
  {
    id: 34046,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "PREMIO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 117,
    package_name: null,
  },
  {
    id: 34045,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "POLIZZA",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 116,
    package_name: null,
  },
  {
    id: 34044,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "PERITO:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 115,
    package_name: null,
  },
  {
    id: 34024,
    parent_id: 34021,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Valore di rimpiazzo a nuovo",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 95,
    package_name: null,
  },
  {
    id: 34023,
    parent_id: 34021,
    product_id: 276,
    benchmark_clause_id: null,
    title: "2      Danni non riparabili (DANNO TOTALE)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 94,
    package_name: null,
  },
  {
    id: 34014,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 12) Rinvio alle norme di Legge",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 85,
    package_name: null,
  },
  {
    id: 34012,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 10) Recesso in caso di sinistro",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 83,
    package_name: null,
  },
  {
    id: 34011,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 9) Rescissione dalla presente estensione di garanzia",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 82,
    package_name: null,
  },
  {
    id: 34010,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 8) Pagamento dell’indennizzo",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 81,
    package_name: null,
  },
  {
    id: 34009,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 7) Limite di indennizzo Danni Indiretti",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 80,
    package_name: null,
  },
  {
    id: 33999,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "d) SPESE GENERALI FISSE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 70,
    package_name: null,
  },
  {
    id: 33998,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "c) DATA D’EFFETTO DELLA COPERTURA L",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 69,
    package_name: null,
  },
  {
    id: 33997,
    parent_id: 33995,
    product_id: 276,
    benchmark_clause_id: null,
    title: "b) DATA DELL’ ARRESTO DELL’ATTIVITA’",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 68,
    package_name: null,
  },
  {
    id: 33976,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 4\tAGGRAVAMENTO DEL RISCHIO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 47,
    package_name: null,
  },
  {
    id: 33975,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 3       MANUTENZIONE DEGLI ENTI ASSICURATI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 46,
    package_name: null,
  },
  {
    id: 33974,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 2\tRISCHI ESCLUSI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 45,
    package_name: null,
  },
  {
    id: 33967,
    parent_id: 33964,
    product_id: 276,
    benchmark_clause_id: null,
    title: "danni ai dati:       ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 38,
    package_name: null,
  },
  {
    id: 33966,
    parent_id: 33964,
    product_id: 276,
    benchmark_clause_id: null,
    title: "danno totale:       ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 37,
    package_name: null,
  },
  {
    id: 33965,
    parent_id: 33964,
    product_id: 276,
    benchmark_clause_id: null,
    title: "danno parziale:   ",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 36,
    package_name: null,
  },
  {
    id: 33964,
    parent_id: 33963,
    product_id: 276,
    benchmark_clause_id: null,
    title: "a)   Hardware:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 35,
    package_name: null,
  },
  {
    id: 33963,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "7)    DETERMINAZIONE DELL'INDENNIZZO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 34,
    package_name: null,
  },
  {
    id: 33962,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "6)    CAPITALE ASSICURATO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 33,
    package_name: null,
  },
  {
    id: 34047,
    parent_id: 34029,
    product_id: 276,
    benchmark_clause_id: null,
    title: "RISARCIMENTO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 118,
    package_name: null,
  },
  {
    id: 33954,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "1)    OGGETTO DELL'ASSICURAZIONE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 25,
    package_name: null,
  },
  {
    id: 33953,
    parent_id: 33951,
    product_id: 276,
    benchmark_clause_id: null,
    title: "2)    SCOPERTO E/O FRANCHIGIA.",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 24,
    package_name: null,
  },
  {
    id: 33942,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "8. Diritto di recesso",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 13,
    package_name: null,
  },
  {
    id: 33941,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "7. Rivalsa",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 12,
    package_name: null,
  },
  {
    id: 33940,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "6. Premi",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 11,
    package_name: null,
  },
  {
    id: 34013,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 11) Diritto di surroga",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 84,
    package_name: null,
  },
  {
    id: 33939,
    parent_id: 33938,
    product_id: 276,
    benchmark_clause_id: null,
    title: "5. Aggravamento e diminuzione del rischio",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 10,
    package_name: null,
  },
  {
    id: 33977,
    parent_id: 33972,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 6       PAGAMENTO DEL PREMIO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 48,
    package_name: null,
  },
  {
    id: 34021,
    parent_id: 34015,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art 6 - DETERMINAZIONE DELL'INDENNIZZO",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 92,
    package_name: null,
  },
  {
    id: 33995,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 2) Definizioni",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 66,
    package_name: null,
  },
  {
    id: 33961,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "5)    RISCHI ESCLUSI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 32,
    package_name: null,
  },
  {
    id: 33936,
    parent_id: 33934,
    product_id: 276,
    benchmark_clause_id: null,
    title: "DANnI INDIRETTI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 7,
    package_name: null,
  },
  {
    id: 33951,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "PARTE  A)",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 22,
    package_name: null,
  },
  {
    id: 34003,
    parent_id: 33993,
    product_id: 276,
    benchmark_clause_id: null,
    title: "Art. 4) Calcolo dell’indennizzo",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 74,
    package_name: null,
  },
  {
    id: 33956,
    parent_id: 33950,
    product_id: 276,
    benchmark_clause_id: null,
    title: "3)    BENI ASSICURATI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 27,
    package_name: null,
  },
  {
    id: 33935,
    parent_id: 33934,
    product_id: 276,
    benchmark_clause_id: null,
    title: "3.  Coperture  assicurative offerte  -  Limitazioni  ed esclusioni",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 6,
    package_name: null,
  },
  {
    id: 33946,
    parent_id: 33930,
    product_id: 276,
    benchmark_clause_id: null,
    title: "C.  INFORMAZIONI  SULLE  PROCEDURE  LIQUIDATIVE  E SUI RECLAMI",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 17,
    package_name: null,
  },
  {
    id: 33931,
    parent_id: 33930,
    product_id: 276,
    benchmark_clause_id: null,
    title: "A. INFORMAZIONI SULL’IMPRESA DI ASSICURAZIONE",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 2,
    package_name: null,
  },
  {
    id: 33938,
    parent_id: 33936,
    product_id: 276,
    benchmark_clause_id: null,
    title:
      "• Garanzia     accessoria     Computer     Portatili     operante esclusivamente se presente in polizza:",
    franchise_type_id: null,
    summary_clause: false,
    rating: 0,
    internal_note: "",
    company_note: "",
    position: 9,
    package_name: null,
  },
];
